### ISSUE TITLE
Feed CiviCRM mentions from Twitter to social media channel

### ISSUE THREAD

**Issue by xurizaemon** [xurizaemon/bolts#1]
- [x] Retrieve mentions and post to MM
- [x] Decide on search terms (currently: `#civicrm OR from:civicrm`)
- [x] Decide on channel to post tweets to

**Comment by joemcl** [comment]
Add #civicamp as search term, please :)

**Comment by xurizaemon** [comment]
Done!

On 9/03/2017 3:07 PM, "Joe McLaughlin" <notifications@github.com> wrote:

Add #civicamp as search term, please :)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/xurizaemon/bolts/issues/1#issuecomment-285232456>, or mute
the thread

**Comment by joemcl** [comment]
Cool, thanks! Just in time for #CiviCamp Manchester.

**Comment by xurizaemon** [comment]
> Where are the search terms stored, anyway?

See the commit above - they live in `.config.sh` (refer to `example-config.sh`)

Would be possible to set them in `robot.brain` as well ... to do that we need to think about who is allowed to set this variable or that. Ref also your question about do we want all people or just some able to reboot @bolts via DM, etc - might make sense to have a configurable set of "botmaster" role users who can set some vars, etc etc?

**Comment by joemcl** [comment]
Thanks @xurizaemon . Yeah botmaster role makes sense if it's not a pain to create.

**Comment by joemcl** [comment]
Hey @xurizaemon - [some] tweets in ~socialmedia don't show direct http link to the tweet - instead, just shows @bph twitter handle link, for example - see screenshot - so I found bph's tweet by clicking on handle and going to tweetsream - but direct http link is much better. 

Also, for tweets with http links to external resource in the tweet text - like pkeogan in tweet list - would be useful to distringuish between http link *to* tweet vs. http link *within* the tweet itself - so perhaps Link to Tweet: http....  to make it easy to RT ? 

![mattermost -socialmedia tweets](https://cloud.githubusercontent.com/assets/3912434/23769070/f41c1070-04c2-11e7-801f-8c68e5a5c270.png)

**Comment by joemcl** [comment]
Re the above - I just figured out that clicking on the date and time hyperlink takes one directly to the tweet :) .

**Comment by xurizaemon** [comment]
Hey, thanks @joemcl! Glad you found the link :)

There are some issues with links in the tweet body, but I think they need to be addressed a couple of projects over! bolts uses vspiewak/hubot-twitter-mention, which in turn uses ttezel/twit.

I added an issue on twitter-mention regarding improving format of hashtags, links in tweet etc: vspiewak/hubot-twitter-mention/#3

Not top of my priority list right now, but something to come back to!

**Comment by joemcl** [comment]
Please add #CiviCon as a search term for @bolts to send stuff to https://chat.civicrm.org/civicrm/channels/socialmedia . Thanks. I'd do it myself but I have not figured out how to update my fork of this with the latest updates, then do a PR to add #CiviCon to .config.sh

**Comment by xurizaemon** [comment]
Done, query is now 

    export HUBOT_TWITTER_MENTION_QUERY="#civicrm OR #civicamp OR from:civicrm OR @civicrm"

We can't PR a change to `.config.sh` because it's not in the repo - in order to prevent revealing details like `HUBOT_WHATEVER_PASSWORD`.

Just asking me via a comment or issue is the right approach!

Use a separate issue, then I get a warm fuzzy from closing them 😜

**Comment by joemcl** [comment]
Thanks @xurizaemon and yeah will do new Issue in the future

**Comment by bph** [comment]
Tthe direct link to the tweet is the date/time stamp

Birgit
aka @bph
