### ISSUE TITLE
Add /remind functionality similar to Slack

### ISSUE THREAD

**Issue by joemcl** [xurizaemon/bolts#13]
Slack has a /remind function - /remind [@user, @channel, etc] [text] [time] which is handy for setting an automatic reminder message for oneself, another user or (with discretion) to @channel or @here , etc.  There is a hubot coffee script that is similar but only sends reminders to 'me' - see https://github.com/github/hubot-scripts/blob/master/src/scripts/remind.coffee

**Comment by xurizaemon** [comment]
Added [`hubot-remind-her`](https://github.com/mx4492/hubot-remind-her) in 7edff060

**Comment by xurizaemon** [comment]
`@bolts remind me in 1 minute to REMINDER TEXT HERE`
