### ISSUE TITLE
Directory

### ISSUE THREAD

**Issue by RandyTobias** [xurizaemon/bolts#16]
Would be useful if we could do something like:
@bolts Who are the Core Team
------------------------
@rtobias81, The core team are (Name, Position, MatterMost Handle):
Coleman Watts, Product Manager, US (colman)
Joshua Gowans, Project Manager, US (josh)
Tim Otten, Software Architect, US (totten)
------------------------
Just because the core team is needed for certain things on MatterMost, and not all of us know who the CT are or how to reach them. This came up for me yesterday when we were discussing setting up a MIH.

**Comment by xurizaemon** [comment]
Sure. Easy way to do this would be:

    rtobias81> @bolts learn core-team = The core team are: Darth Vader (Construction Supervisor, @darthdaddy); Emperor Palpatine (Motivational Specialist, @insidious); Jar-Jar Binks (Unspecified, @plagueis99)
    rtobias81> ?core-team

An intermediate approach would be to put forward an additional plugin which lets you do factoids in a more natural language format. (Factoids could do this, but currently it requires the factoid prefix, currently `(!|?)` I think.)

A roll-your-own approach would be to PR a respond command in a new file to xurizaemon/hubot-bolts, which is a catchall for random scripts we want hubot to run. If it's not a plugin on its own, you can add to that plugin instead. This just needs to be a simple plugin file with docs as per [restart.coffee](https://github.com/xurizaemon/hubot-bolts/blob/master/src/restart.coffee)

    module.exports = (robot) ->
      robot.respond /Who are the Core Team/i, (msg) ->
        msg.send "The core team are ..."

**Comment by RandyTobias** [comment]
I love the way you think. I don't know why it didn't even occur to me that we could use the already existing Factoids functionality. The only question I have with how that would work (and why I skipped the @ in the original issue) is would including the @ notify all of the core team each time someone just wants to see who they are (or tests this feature)? 

The natural language format would be nice, but beyond the scope of functionality I was thinking of. I think the only thing that I would suggest beyond just creating a Factiod, is just to list in in ?bolts. Then you don't really have to worry about the command having to be parsed in any special way.

**Comment by xurizaemon** [comment]
Yeah, MM does trigger notifications for mentions like that (it can't tell a comment like that from any other). So you'd want to be careful about mentioning Voldemort ...

Mattermost seems to send mention emails even without the @ I think?

?bolts is for info about bolts,  I don't think core team info belongs there, maybe I misunderstand?

**Comment by RandyTobias** [comment]
Not ?bolts. My mistake. I meant added to the list of commands.
