### ISSUE TITLE
Add instagram RSS feeds

### ISSUE THREAD

**Issue by xurizaemon** [xurizaemon/bolts#17]
We can pull instagram posts in from RSS, by way of instagram-to-RSS service.

Because of social stuff around CiviCon 🎡

**Comment by xurizaemon** [comment]
It would be nice if the feed included users names so we could better credit, but it doesn't seem to?

* https://queryfeed.net/instagram?q=%23civicrm

Maybe a better feed in future.

**Comment by joemcl** [comment]
Hey not sure if it's my Mattermost settings - I'll check - but this is how the instagram pics look to me at https://chat.civicrm.org/civicrm/channels/socialmedia 
![bolts-instagram](https://cloud.githubusercontent.com/assets/3912434/26270548/8fda08bc-3cb0-11e7-8049-0c98bf7b7018.png)

**Comment by joemcl** [comment]
It looks great on a phone though...

![screenshot_20170519-173523](https://cloud.githubusercontent.com/assets/3912434/26271403/36e8871a-3cba-11e7-964e-93cb2bfe1a20.png)

**Comment by xurizaemon** [comment]
Yep - I should throw a line break in [the template](https://github.com/xurizaemon/bolts/blob/a461fe143edcda21ad6532b45b779e9bebb439d3/hubotrssconfig.json#L30).

You don't get margin settings I think, it's not HTML, but you can play with the MD formatting just by PM-ing yourself or bolts or just posting in ~x-bot-test.
