### ISSUE TITLE
Bolts getting locked out

### ISSUE THREAD

**Issue by xurizaemon** [xurizaemon/bolts#25]
Bolts gets locked out (not logged out) for "too many password attempts" and can't reauthenticate.

I suspect this might be the same as #15 - something triggers a login cycle ahead of schedule? And we spam logins and get locked.

Mattermost config.json has `MaximumLoginAttempts` variable.

**Comment by xurizaemon** [comment]
Process to get bolts back in after a lockout:

- visit Mattermost system console
- click users
- search for "bolts"
- use side menu to set password
- bolts will log back in after a delay, or quickly if restarted

**Comment by xurizaemon** [comment]
(could be done by password reset also I think, but quicker via admin UI)

**Comment by xurizaemon** [comment]
Hmm, this happened again recently, after 18mo of not happening. Poop.

**Comment by joemcl** [comment]
Process to get bolts back in after a lockout:

- visit Mattermost system console
- click View Members 
- enter "bolts" into Search users
- use side menu to set password
- bolts will log back in after a delay, or quickly if restarted

**Comment by MikeyMJCO** [comment]
Fixed with move to bot user and token auth
