### ISSUE TITLE
Announce Stack Exchange questions?

### ISSUE THREAD

**Issue by xurizaemon** [xurizaemon/bolts#5]
Watch the SE site and report new questions?

**Comment by joemcl** [comment]
This, kind of? https://github.com/jdanlewis/hubot-slack-overflow

**Comment by xurizaemon** [comment]
[se-tags-to-mm-channels.xlsx](https://github.com/xurizaemon/bolts/files/923331/se-tags-to-mm-channels.xlsx)

@seanmadsen made a spreadsheet to map SE tags to channels. Had to convert to .xlsx because @github objected to .ods spreads.

We could either implement this by having [a channel selection method somewhere around here](https://github.com/xurizaemon/hubot-rss-poller2/blob/master/lib/rss-feed-poller.js#L70), or by using a tool like `hubot-refrain` to modify the outbound message (again, not sure if we can pass tags as metadata alongside a message).
